a=int(input('enter the first value:'))
b=int(input('enter the second value:'))
print('addition of two numbers{}+{}={}'.format(a,b,a+b))
print(('substraction of two numbers {}-{}={}'.format(a,b,a-b)))
print('multiplication of two numbers {}*{}={}'.format(a,b,a*b))
print('division of two numbers {}/{}={}'.format(a,b,a/b))
print('floor division of two numbers={}//{}={}'.format(a,b,a//b))
print('modulo division of two numbers={}%{}={}'.format(a,b,a%b))
print('power {}**{}={}'.format(a,b,a**b))
